seed: 42
device: "cuda"

name: nmnist_ff_supervised_top_down_randomized

input:
  path: datasets
  batch_size: 100
  dataset: "nmnist"

model:
  hidden_dim: 2000
  num_layers: 3
  top_down: True

training:
  epochs: 200
  frame_switch: -1

  learning_rate: 5e-5
  weight_decay: 3e-4
  momentum: 0.9

  randomized: True

  backpropagation: False
  unsupervised: False

hydra:
  run:
    dir: logs