seed: 42
device: "cuda"

name: nmnist_ff_unsupervised_top_down_frame_switch

input:
  path: datasets
  batch_size: 100
  dataset: "nmnist"

model:
  hidden_dim: 2000
  num_layers: 3
  top_down: True

training:
  epochs: 200
  frame_switch: 20

  learning_rate: 1e-4
  weight_decay: 3e-4
  momentum: 0.9

  randomized: False

  backpropagation: False
  unsupervised: True

hydra:
  run:
    dir: logs